### PR TITLE
Testing Pull Request

### PR DESCRIPTION
**Pull request by aracelicaes**
This pull request was created to check all commits and testing the whole game using Rspec. 
We are testing:
-draw
-looser
-winner
-all public methods
*For Reviewer
We have created an alternative way to test the game by adding a parameter in the Game.New instance. With these you'll be able to automatize the game to throw: Winner x, Winner o, Looser X, Looser o, Draw when X begins and Draw when O begins. All you have to do is add a parameter into line 5 `Game.New` that is found in our `main` file to test them and then run the `ruby main` file in the console. The parameters that we have built-in for testing are:

- `Game.New('testing')`  Plays, displays winner x
- `Game.New('alt')`  Plays, displays winner o
- `Game.New('loser')` Plays, displays looser x
- `Game.New('altloser')` Plays, displays looser o
- `Game.New('draw')` Plays, displays draw when X starts the Game
- `Game.New('altdraw')` Plays, displays draw when 0 starts the Game

We have also added these parameters in the `game_spec.rb `file to facilitate the rspec testing for you. Please reach out if you have any questions. 
Thanks!

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [x]  Pull Request should have a  meaningful title and a short description
- [x] All the public methods of the classes implemented in project OOP should be tested.
- [x] Player  class should be included in the test
- [x] Lets write test for when there is a loser.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by wickathou** [comment]
Hi @kobiyoyo , do we need to test the public methods even if we are testing them all through other methods?

We tested based on what the game should output, not by the methods it has.

**Comment by kobiyoyo** [comment]
Hi @wickathou,Hope you re  doing great?All the public methods of the classes implemented in project OOP should be tested.

**Comment by shshamim63** [comment]
## Status :heavy_check_mark: Approved :1234: 
___
Hi @aracelicaes and @wickathou :wave: 
Congratulation you have covered all the changes asked by the previous reviewer. I just got a suggestion to make.
___
### :point_right: Suggestion :point_left: 
___
- It is best practice to generate separate testing files for each of your files. For example, to generate a testing file for player should be player_spec.rb. So if you want to execute a specific test related to a specific file you can run `rspec spec/player_spec.rb -fdoc`
___
This :+1: is from me you can go ahead.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Pull request merged**
